// Generated by HEIDI for job job_1787696805096_1dfb2caa
// Product: 3D-Printable Model Preparation Package
// Request: A small box container 40x30x20mm
// Model type: box
// Generated: 2026-08-25T22:26:45.196Z
//
// This is a parameterized OpenSCAD model. You can adjust the
// parameters below to customize the dimensions before rendering.

// ─── Parameters ───
width = 40;       // X dimension in mm
height = 30;     // Y dimension in mm
depth = 20;       // Z dimension in mm
wall = 2;    // wall thickness in mm
$fn = 60;               // facet resolution

// Parametric hollow box
module parametric_box() {
    difference() {
        // Outer shell
        cube([width, height, depth]);
        // Inner cavity
        translate([wall, wall, wall])
            cube([width - wall * 2, height - wall * 2, depth - wall + 1]);
    }
}
parametric_box();
