// CRITICAL: Rotate exposed secrets immediately
//
// SECURITY FIX: this script previously printed the freshly generated
// break-glass token and service-role key straight to stdout via
// console.log(), which means every terminal scrollback, CI log, and log
// aggregator that captured a run of this script also captured live
// credentials -- the exact class of exposure this script exists to clean up
// after. Secret values are now written only to a local, gitignored file
// (mode 0600, matched by the `.env.*` rule in .gitignore) and never logged.
const { createClient } = require('@supabase/supabase-js');
const crypto = require('crypto');
const fs = require('fs');
const path = require('path');

async function rotateSecrets() {
  console.log('🚨 CRITICAL: ROTATING EXPOSED SECRETS');
  console.log('=====================================');
  console.log('⚠️  REAL TOKENS/KEYS WERE SHARED IN LOGS');
  console.log('');

  const supabase = createClient(
    'https://akbnfovjdcobifeupvbn.supabase.co',
    process.env.SUPABASE_SERVICE_ROLE_KEY
  );
  void supabase; // Reserved for a future direct-rotation API call; not used yet (see MANUAL STEPS below).

  // Generate new secure tokens
  const newBreakGlassToken = crypto.randomBytes(32).toString('hex');
  const newServiceRoleKey = crypto.randomBytes(32).toString('hex');

  // Write secrets to a local, gitignored file instead of stdout/logs.
  const outputPath = path.join(__dirname, '.env.rotation-output');
  const outputContents =
    `# Generated by rotate-secrets.js at ${new Date().toISOString()}\n` +
    `# Do not commit. Copy these into the Supabase dashboard / secrets manager,\n` +
    `# then delete this file.\n` +
    `NEW_BREAK_GLASS_TOKEN=${newBreakGlassToken}\n` +
    `NEW_SERVICE_ROLE_KEY_CANDIDATE=${newServiceRoleKey}\n`;

  fs.writeFileSync(outputPath, outputContents, { mode: 0o600 });

  console.log('🔐 NEW SECRETS GENERATED');
  console.log('========================');
  console.log(`   Written to: ${outputPath} (permissions 600, not logged, gitignored)`);
  console.log('');

  try {
    // Note: actual rotation still requires manual steps in the Supabase dashboard.
    console.log('MANUAL STEPS REQUIRED:');
    console.log('1. Go to Supabase Dashboard → Settings → API');
    console.log('2. Regenerate service_role key (Supabase generates its own value here;');
    console.log('   NEW_SERVICE_ROLE_KEY_CANDIDATE in the output file is a local fallback only)');
    console.log('3. Go to Supabase Dashboard → Edge Functions → Secrets');
    console.log(`4. Update KEEPER_BREAK_GLASS_TOKEN using the value in ${outputPath}`);
    console.log('5. Update .env file with the new values');
    console.log(`6. Delete ${outputPath} once the values have been transcribed`);
    console.log('');
    console.log('⚠️  ALL EXISTING TOKENS ARE NOW COMPROMISED');
    console.log('   Rotate them immediately in production!');

  } catch (error) {
    console.error('❌ Secret rotation failed:', error.message);
  }
}

rotateSecrets();
