// Generated by HEIDI for job job_1787719485944_4a9840d2
// Product: 3D-Printable Model Preparation Package
// Request: E2E production path qualification test — automated cleanup expected
// Model type: box
// Generated: 2026-09-07T04:35:14.802Z
//
// This is a parameterized OpenSCAD model. You can adjust the
// parameters below to customize the dimensions before rendering.

// ─── Parameters ───
width = 50;       // X dimension in mm
height = 50;     // Y dimension in mm
depth = 10;       // Z dimension in mm
wall = 3;    // wall thickness in mm
$fn = 60;               // facet resolution

// Parametric hollow box
module parametric_box() {
    difference() {
        // Outer shell
        cube([width, height, depth]);
        // Inner cavity
        translate([wall, wall, wall])
            cube([width - wall * 2, height - wall * 2, depth - wall + 1]);
    }
}
parametric_box();
