/**
 * HEIDI Memory Layer
 * SQLite + simple vector similarity (cosine on normalized embeddings)
 */

let sqlite3 = null;
try {
  sqlite3 = require('sqlite3').verbose();
} catch (e) {
  console.warn('[HEIDI Memory] sqlite3 not available, using in-memory mode');
}
const path = require('path');
const fs = require('fs');

function cosineSimilarity(vecA, vecB) {
  if (!vecA || !vecB || vecA.length !== vecB.length) return 0;

  let dotProduct = 0;
  let normA = 0;
  let normB = 0;

  for (let i = 0; i < vecA.length; i++) {
    dotProduct += vecA[i] * vecB[i];
    normA += vecA[i] * vecA[i];
    normB += vecB[i] * vecB[i];
  }

  if (normA === 0 || normB === 0) return 0;
  return dotProduct / (Math.sqrt(normA) * Math.sqrt(normB));
}

class HeidiMemory {
  constructor(config = {}) {
    this.dbPath = config.dbPath || path.join(__dirname, '../data/heidi_memory.db');
    this.db = null;
    this.initialized = false;
  }

  async initialize() {
    if (this.initialized) return;
    
    // Fallback to in-memory if sqlite3 not available
    if (!sqlite3) {
      this.inMemoryData = {
        short_term: [],
        long_term: [],
        reflections: [],
        system_state: []
      };
      this.initialized = true;
      console.warn('');
      console.warn('╔══════════════════════════════════════════════════════════════╗');
      console.warn('║  ⚠️  WARNING: RUNNING IN MEMORY-ONLY MODE (NO PERSISTENCE)   ║');
      console.warn('║                                                              ║');
      console.warn('║  Heidi will forget everything when restarted.                ║');
      console.warn('║  Install sqlite3 for persistent memory:                      ║');
      console.warn('║    npm install sqlite3                                       ║');
      console.warn('╚══════════════════════════════════════════════════════════════╝');
      console.warn('');
      return;
    }

    // Ensure data directory exists
    const dataDir = path.dirname(this.dbPath);
    if (!fs.existsSync(dataDir)) {
      fs.mkdirSync(dataDir, { recursive: true });
    }

    return new Promise((resolve, reject) => {
      if (!sqlite3) return resolve();
      this.db = new sqlite3.Database(this.dbPath, (err) => {
        if (err) {
          console.error('[HEIDI Memory] Failed to open database:', err);
          reject(err);
        } else {
          console.log('[HEIDI Memory] Connected to SQLite');
          this.createTables().then(() => {
            this.initialized = true;
            resolve();
          }).catch(reject);
        }
      });
    });
  }

  async createTables() {
    const tables = [
      // Short term memory - recent interactions
      `CREATE TABLE IF NOT EXISTS short_term (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        input TEXT NOT NULL,
        response TEXT,
        context TEXT,
        confidence REAL,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
      )`,
      
      // Long term memory - important facts
      `CREATE TABLE IF NOT EXISTS long_term (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        fact TEXT NOT NULL,
        category TEXT,
        importance REAL DEFAULT 0.5,
        access_count INTEGER DEFAULT 0,
        last_accessed DATETIME,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
      )`,
      
      // Reflections - insights generated by Heidi
      `CREATE TABLE IF NOT EXISTS reflections (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        insight TEXT NOT NULL,
        confidence REAL,
        action TEXT,
        pattern_type TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
      )`,
      
      // System state - health, logs, metrics
      `CREATE TABLE IF NOT EXISTS system_state (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        state_type TEXT NOT NULL,
        state_data TEXT,
        severity TEXT DEFAULT 'info',
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
      )`,
      
      // Embeddings for vector search (simplified - store as JSON array)
      `CREATE TABLE IF NOT EXISTS embeddings (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        content TEXT NOT NULL,
        embedding TEXT, -- JSON array of floats
        source_table TEXT,
        source_id INTEGER,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
      )`
    ];

    for (const sql of tables) {
      await this.run(sql);
    }

    // Create indexes
    await this.run(`CREATE INDEX IF NOT EXISTS idx_short_term_created ON short_term(created_at)`);
    await this.run(`CREATE INDEX IF NOT EXISTS idx_long_term_category ON long_term(category)`);
    await this.run(`CREATE INDEX IF NOT EXISTS idx_reflections_pattern ON reflections(pattern_type)`);
    await this.run(`CREATE INDEX IF NOT EXISTS idx_system_state_type ON system_state(state_type)`);
    
    console.log('[HEIDI Memory] Tables created');
  }

  run(sql, params = []) {
    return new Promise((resolve, reject) => {
      this.db.run(sql, params, function(err) {
        if (err) reject(err);
        else resolve({ id: this.lastID, changes: this.changes });
      });
    });
  }

  get(sql, params = []) {
    return new Promise((resolve, reject) => {
      this.db.get(sql, params, (err, row) => {
        if (err) reject(err);
        else resolve(row);
      });
    });
  }

  all(sql, params = []) {
    return new Promise((resolve, reject) => {
      this.db.all(sql, params, (err, rows) => {
        if (err) reject(err);
        else resolve(rows);
      });
    });
  }

  // Short term memory operations
  async storeShortTerm(input, response, context = null, confidence = null) {
    if (!sqlite3 && this.inMemoryData) {
      const id = this.inMemoryData.short_term.length + 1;
      this.inMemoryData.short_term.push({
        id, input, response, context: JSON.stringify(context), confidence,
        created_at: new Date().toISOString()
      });
      // Keep only last 1000
      if (this.inMemoryData.short_term.length > 1000) {
        this.inMemoryData.short_term = this.inMemoryData.short_term.slice(-1000);
      }
      return id;
    }
    
    const result = await this.run(
      `INSERT INTO short_term (input, response, context, confidence) VALUES (?, ?, ?, ?)`,
      [input, response, JSON.stringify(context), confidence]
    );
    
    // Keep only last 1000 entries
    await this.run(`DELETE FROM short_term WHERE id NOT IN (SELECT id FROM short_term ORDER BY created_at DESC LIMIT 1000)`);
    
    return result.id;
  }

  async getRecentContext(limit = 10) {
    if (!sqlite3 && this.inMemoryData) {
      return this.inMemoryData.short_term
        .slice().reverse()
        .slice(0, limit);
    }
    
    return this.all(
      `SELECT input, response, context, confidence, created_at 
       FROM short_term 
       ORDER BY created_at DESC 
       LIMIT ?`,
      [limit]
    );
  }

  // Long term memory operations
  async storeFact(fact, category = 'general', importance = 0.5) {
    if (!sqlite3 && this.inMemoryData) {
      const id = this.inMemoryData.long_term.length + 1;
      this.inMemoryData.long_term.push({
        id, fact, category, importance,
        created_at: new Date().toISOString()
      });
      return id;
    }
    
    const result = await this.run(
      `INSERT INTO long_term (fact, category, importance) VALUES (?, ?, ?)`,
      [fact, category, importance]
    );
    return result.id;
  }

  async getFactsByCategory(category, limit = 10) {
    return this.all(
      `SELECT fact, importance, created_at FROM long_term 
       WHERE category = ? 
       ORDER BY importance DESC, access_count DESC 
       LIMIT ?`,
      [category, limit]
    );
  }

  async getTopFacts(limit = 5) {
    return this.all(
      `SELECT fact AS content, importance AS confidence, category AS division FROM long_term
       ORDER BY importance DESC, access_count DESC
       LIMIT ?`,
      [limit]
    );
  }

  async getFactCount() {
    const row = await this.get(`SELECT COUNT(*) AS n FROM long_term`);
    return row ? row.n : 0;
  }

  // Local procedural memory: fact + embedding, keyed by (fact, division) for dedup
  async storeFactWithEmbedding(content, division, confidence, embedding) {
    const category = division || 'global';
    const existing = await this.get(
      `SELECT id FROM long_term WHERE fact = ? AND category = ?`,
      [content, category]
    );

    let factId;
    if (existing) {
      await this.run(
        `UPDATE long_term SET importance = ?, last_accessed = CURRENT_TIMESTAMP WHERE id = ?`,
        [confidence, existing.id]
      );
      factId = existing.id;
    } else {
      const result = await this.run(
        `INSERT INTO long_term (fact, category, importance) VALUES (?, ?, ?)`,
        [content, category, confidence]
      );
      factId = result.id;
    }

    if (embedding) {
      const existingEmbedding = await this.get(
        `SELECT id FROM embeddings WHERE source_table = 'long_term' AND source_id = ?`,
        [factId]
      );
      if (existingEmbedding) {
        await this.run(`UPDATE embeddings SET embedding = ? WHERE id = ?`, [JSON.stringify(embedding), existingEmbedding.id]);
      } else {
        await this.run(
          `INSERT INTO embeddings (content, embedding, source_table, source_id) VALUES (?, ?, 'long_term', ?)`,
          [content, JSON.stringify(embedding), factId]
        );
      }
    }

    return factId;
  }

  // Semantic retrieval over locally stored embeddings (no pgvector required)
  async searchFactsBySimilarity(queryEmbedding, threshold = 0.6, limit = 5) {
    const rows = await this.all(
      `SELECT lt.id, lt.fact AS content, lt.importance AS confidence, lt.category AS division, e.embedding
       FROM embeddings e
       JOIN long_term lt ON lt.id = e.source_id AND e.source_table = 'long_term'`
    );

    return rows
      .map(row => {
        let embedding;
        try { embedding = JSON.parse(row.embedding); } catch { return null; }
        return {
          id: row.id,
          content: row.content,
          confidence: row.confidence,
          division: row.division,
          similarity: cosineSimilarity(queryEmbedding, embedding)
        };
      })
      .filter(r => r && r.similarity > threshold)
      .sort((a, b) => (b.similarity - a.similarity) || (b.confidence - a.confidence))
      .slice(0, limit)
      .map(({ similarity, ...fact }) => fact);
  }

  async searchFacts(query, limit = 5) {
    // Simple keyword search (can be enhanced with vector search later)
    const keywords = query.toLowerCase().split(' ').filter(w => w.length > 3);
    if (keywords.length === 0) return [];
    
    if (!sqlite3 && this.inMemoryData) {
      return this.inMemoryData.long_term
        .filter(item => keywords.some(k => item.fact.toLowerCase().includes(k)))
        .slice(0, limit);
    }
    
    const conditions = keywords.map(() => `LOWER(fact) LIKE ?`).join(' OR ');
    const params = keywords.map(k => `%${k}%`);
    
    return this.all(
      `SELECT fact, category, importance FROM long_term 
       WHERE ${conditions}
       ORDER BY importance DESC, access_count DESC 
       LIMIT ?`,
      [...params, limit]
    );
  }

  // Reflection operations
  async storeReflection(insight, confidence, action = null, patternType = null) {
    if (!sqlite3 && this.inMemoryData) {
      const id = this.inMemoryData.reflections.length + 1;
      this.inMemoryData.reflections.push({
        id, insight, confidence, action, pattern_type: patternType,
        created_at: new Date().toISOString()
      });
      return id;
    }
    
    const result = await this.run(
      `INSERT INTO reflections (insight, confidence, action, pattern_type) VALUES (?, ?, ?, ?)`,
      [insight, confidence, action, patternType]
    );
    return result.id;
  }

  async getRecentReflections(limit = 10) {
    if (!sqlite3 && this.inMemoryData) {
      return this.inMemoryData.reflections
        .slice().reverse()
        .slice(0, limit);
    }
    
    return this.all(
      `SELECT insight, confidence, action, pattern_type, created_at 
       FROM reflections 
       ORDER BY created_at DESC 
       LIMIT ?`,
      [limit]
    );
  }

  async getReflectionsByPattern(patternType, limit = 5) {
    return this.all(
      `SELECT insight, confidence, action, created_at 
       FROM reflections 
       WHERE pattern_type = ? 
       ORDER BY confidence DESC 
       LIMIT ?`,
      [patternType, limit]
    );
  }

  // System state operations
  async storeSystemState(stateType, stateData, severity = 'info') {
    const result = await this.run(
      `INSERT INTO system_state (state_type, state_data, severity) VALUES (?, ?, ?)`,
      [stateType, JSON.stringify(stateData), severity]
    );
    return result.id;
  }

  async getRecentSystemState(stateType, limit = 10) {
    return this.all(
      `SELECT state_data, severity, created_at 
       FROM system_state 
       WHERE state_type = ? 
       ORDER BY created_at DESC 
       LIMIT ?`,
      [stateType, limit]
    );
  }

  // Build context for LLM
  async buildContext(input, maxTokens = 2000) {
    const context = {
      recent_interactions: [],
      relevant_facts: [],
      recent_reflections: [],
      system_health: []
    };

    // Get recent interactions
    context.recent_interactions = await this.getRecentContext(5);

    // Get relevant facts based on input keywords
    context.relevant_facts = await this.searchFacts(input, 3);

    // Get recent high-confidence reflections
    const reflections = await this.getRecentReflections(3);
    context.recent_reflections = reflections.filter(r => r.confidence > 0.7);

    // Get recent system state
    context.system_health = await this.getRecentSystemState('health', 1);

    return context;
  }

  async close() {
    if (!sqlite3 && this.inMemoryData) {
      this.inMemoryData = null;
      this.initialized = false;
      return;
    }
    
    if (this.db) {
      return new Promise((resolve) => {
        this.db.close((err) => {
          if (err) console.error('[HEIDI Memory] Error closing database:', err);
          resolve();
        });
      });
    }
  }
}

module.exports = HeidiMemory;
