// Generated by HEIDI for job job_1787696804524_f24e43bb
// Product: 3D-Printable Model Preparation Package
// Request: A simple L-shaped bracket for mounting a shelf on the wall
// Model type: bracket
// Generated: 2026-08-25T22:26:44.794Z
//
// This is a parameterized OpenSCAD model. You can adjust the
// parameters below to customize the dimensions before rendering.

// ─── Parameters ───
width = 60;       // X dimension in mm
height = 40;     // Y dimension in mm
depth = 8;       // Z dimension in mm
wall = 4;    // wall thickness in mm
$fn = 60;               // facet resolution

// L-shaped bracket
module bracket() {
    difference() {
        union() {
            // Horizontal arm
            cube([width, wall, depth]);
            // Vertical arm
            cube([wall, height, depth]);
        }
        // Mounting holes
        translate([width * 0.75, wall / 2, depth / 2])
            rotate([90, 0, 0])
                cylinder(h = wall + 2, d = 4);
        translate([wall / 2, height * 0.75, depth / 2])
            rotate([0, 90, 0])
                cylinder(h = wall + 2, d = 4);
    }
}
bracket();
