import { Campaign } from './types';

const TODAY = '2026-05-23';

const campaigns: Campaign[] = [
  {
    id: 'toyota-usa',
    name: 'Toyota USA Foundation',
    funder: 'Toyota Foundation',
    amount: 50000,
    deadline: '2026-06-15',
    status: 'partnerships_needed',
    category: 'grant',
    description: 'Community safety and education grant from Toyota USA Foundation requiring school district and FEMA partnerships.',
    probability: 85,
    completionPct: 40,
    priority: 'urgent',
    missingItems: [
      'Partnership letters from Toyota TMMTX',
      'School district letters (0/10)',
      'FEMA partnership confirmation',
    ],
    contacts: ['Toyota TMMTX Partnerships', 'Schulenburg ISD', 'Fayette County Commissioners'],
    tags: ['community', 'safety', 'education'],
  },
  {
    id: 'danos-gives',
    name: 'Danos GIVES',
    funder: 'Danos & Curole',
    amount: 10000,
    deadline: '2026-06-20',
    status: 'ready',
    category: 'grant',
    description: 'Community impact grant from Danos GIVES program, nearly complete and ready for submission.',
    probability: 95,
    completionPct: 90,
    priority: 'urgent',
    missingItems: ['Final application review', 'Board signature'],
    tags: ['community'],
  },
  {
    id: 'fema-empg',
    name: 'FEMA EMPG',
    funder: 'FEMA',
    amount: 100000,
    deadline: '2026-06-30',
    status: 'in_progress',
    category: 'grant',
    description: 'Emergency Management Performance Grant supporting local emergency preparedness infrastructure.',
    probability: 75,
    completionPct: 55,
    priority: 'high',
    missingItems: ['Budget justification narrative', 'Community impact metrics'],
    tags: ['emergency', 'infrastructure'],
  },
  {
    id: 'nhtsa-safety',
    name: 'NHTSA Roadway Safety',
    funder: 'NHTSA',
    amount: 300000,
    deadline: '2026-07-05',
    status: 'planned',
    category: 'grant',
    description: 'National Highway Traffic Safety Administration grant for roadway safety improvements.',
    probability: 60,
    completionPct: 20,
    priority: 'high',
    tags: ['safety', 'transportation'],
  },
  {
    id: 'nsf-wind',
    name: 'NSF Advanced Research',
    funder: 'NSF',
    amount: 1200000,
    deadline: '2026-07-20',
    status: 'planned',
    category: 'grant',
    description: 'National Science Foundation advanced research grant for wind energy and innovative technology.',
    probability: 55,
    completionPct: 15,
    priority: 'high',
    tags: ['research', 'energy', 'innovation'],
  },
  {
    id: 'doe-energy',
    name: 'DOE Energy Innovation',
    funder: 'Dept of Energy',
    amount: 500000,
    deadline: '2026-08-01',
    status: 'planned',
    category: 'grant',
    description: 'Department of Energy grant for innovative energy solutions and clean technology development.',
    probability: 50,
    completionPct: 10,
    priority: 'medium',
    tags: ['energy', 'clean-tech'],
  },
  {
    id: 'hud-community',
    name: 'HUD Community Dev',
    funder: 'HUD',
    amount: 750000,
    deadline: '2026-08-15',
    status: 'planned',
    category: 'grant',
    description: 'HUD Community Development Block Grant for affordable housing and neighborhood revitalization.',
    probability: 45,
    completionPct: 5,
    priority: 'medium',
    tags: ['community', 'housing'],
  },
  {
    id: 'usda-rural',
    name: 'USDA Rural Dev',
    funder: 'USDA',
    amount: 400000,
    deadline: '2026-09-01',
    status: 'planned',
    category: 'grant',
    description: 'USDA Rural Development grant for infrastructure and economic development in rural communities.',
    probability: 50,
    completionPct: 0,
    priority: 'medium',
    tags: ['rural', 'infrastructure'],
  },
  {
    id: 'eda-tech',
    name: 'EDA Tech Innovation',
    funder: 'EDA',
    amount: 1000000,
    deadline: '2026-09-15',
    status: 'planned',
    category: 'grant',
    description: 'Economic Development Administration grant for technology innovation and workforce development.',
    probability: 45,
    completionPct: 0,
    priority: 'medium',
    tags: ['tech', 'workforce'],
  },
  {
    id: 'nasa-sbir',
    name: 'NASA SBIR Phase I',
    funder: 'NASA',
    amount: 500000,
    deadline: '2026-10-01',
    status: 'planned',
    category: 'grant',
    description: 'NASA Small Business Innovation Research Phase I grant for aerospace technology development.',
    probability: 40,
    completionPct: 0,
    priority: 'low',
    tags: ['aerospace', 'research'],
  },
  {
    id: 'nih-sttr',
    name: 'NIH STTR Research',
    funder: 'NIH',
    amount: 250000,
    deadline: '2026-10-15',
    status: 'planned',
    category: 'grant',
    description: 'NIH Small Business Technology Transfer Research grant for health technology innovations.',
    probability: 40,
    completionPct: 0,
    priority: 'low',
    tags: ['health', 'research'],
  },
  {
    id: 'sba-innov',
    name: 'SBA Innovation Fund',
    funder: 'SBA',
    amount: 300000,
    deadline: '2026-11-01',
    status: 'planned',
    category: 'grant',
    description: 'Small Business Administration innovation fund for entrepreneurship and small business growth.',
    probability: 45,
    completionPct: 0,
    priority: 'low',
    tags: ['small-business', 'innovation'],
  },
  {
    id: 'dot-smart',
    name: 'DOT Smart Mobility',
    funder: 'DOT',
    amount: 2000000,
    deadline: '2026-12-01',
    status: 'planned',
    category: 'grant',
    description: 'Department of Transportation smart mobility grant for connected and autonomous vehicle infrastructure.',
    probability: 35,
    completionPct: 0,
    priority: 'low',
    tags: ['transportation', 'smart-city'],
  },
  {
    id: 'army-corps',
    name: 'Army Corps Tech',
    funder: 'Army Corps',
    amount: 1340000,
    deadline: '2027-01-15',
    status: 'planned',
    category: 'grant',
    description: 'Army Corps of Engineers technology grant for water infrastructure and civil engineering innovation.',
    probability: 35,
    completionPct: 0,
    priority: 'low',
    tags: ['infrastructure', 'water'],
  },
  {
    id: 'heb-corp',
    name: 'H-E-B Corporate',
    funder: 'H-E-B Foundation',
    amount: 750000,
    deadline: '2026-07-01',
    status: 'in_progress',
    category: 'corporate',
    description: 'H-E-B Foundation corporate social responsibility partnership for community food security and education.',
    probability: 70,
    completionPct: 35,
    priority: 'high',
    tags: ['corporate', 'community', 'food-security'],
  },
  {
    id: 'exxon-corp',
    name: 'ExxonMobil CSR',
    funder: 'ExxonMobil',
    amount: 800000,
    deadline: '2026-08-01',
    status: 'planned',
    category: 'corporate',
    description: 'ExxonMobil corporate social responsibility program supporting STEM education and workforce development.',
    probability: 50,
    completionPct: 10,
    priority: 'high',
    tags: ['corporate', 'stem', 'workforce'],
  },
  {
    id: 'microsoft-corp',
    name: 'Microsoft Philanthropies',
    funder: 'Microsoft',
    amount: 750000,
    deadline: '2026-09-01',
    status: 'planned',
    category: 'corporate',
    description: 'Microsoft Philanthropies grant for digital equity and technology access in underserved communities.',
    probability: 55,
    completionPct: 5,
    priority: 'medium',
    tags: ['corporate', 'digital-equity', 'tech'],
  },
  {
    id: 'amazon-corp',
    name: 'AWS Community Impact',
    funder: 'Amazon',
    amount: 700000,
    deadline: '2026-10-01',
    status: 'planned',
    category: 'corporate',
    description: 'Amazon AWS Community Impact program supporting cloud computing access and technical skills development.',
    probability: 45,
    completionPct: 0,
    priority: 'medium',
    tags: ['corporate', 'cloud', 'tech'],
  },
];

export function getAllCampaigns(): Campaign[] {
  return campaigns;
}

export function getGrantCampaigns(): Campaign[] {
  return campaigns.filter((c) => c.category === 'grant');
}

export function getCorporateCampaigns(): Campaign[] {
  return campaigns.filter((c) => c.category === 'corporate');
}

export function daysUntil(deadline: string): number {
  const today = new Date(TODAY);
  const due = new Date(deadline);
  const diff = due.getTime() - today.getTime();
  return Math.ceil(diff / (1000 * 60 * 60 * 24));
}

export function getUrgentCampaigns(): Campaign[] {
  return campaigns.filter((c) => daysUntil(c.deadline) <= 14);
}

export function getPipelineStats() {
  return {
    totalPipeline: 11700000,
    totalGrants: 8700000,
    totalCorporate: 3000000,
    expectedGrants: 6090000,
    expectedCorporate: 1500000,
    annualRevenue: 1500000,
    revenueContracted: 450000,
  };
}
