/**
 * Migration test: heidi_missions — durable mission record.
 *
 * Tier-1 safe by default: static assertions against the migration SQL
 * text only — no database connection. The live-schema block runs ONLY
 * when HYDI_MISSION_TEST_DSN points at a demonstrably disposable
 * database (a dedicated test instance/container). It hard-refuses the
 * active local HYDI Postgres (127.0.0.1:54322/postgres) and any DSN
 * that does not look isolated, and it still wraps DDL in a transaction
 * that is rolled back — belt-and-suspenders even on a disposable target.
 *
 * An earlier version of this test ran the migration on the ACTIVE local
 * database inside BEGIN/ROLLBACK. That was wrong: a rollback does not
 * make live-DB DDL an isolated test — it took real schema locks on the
 * active instance and executed the DDL where a crash could have
 * committed it. The live block below never runs by default.
 */

'use strict';

const { readMigration } = require('./helpers');

const SQL = readMigration('20260930000000_heidi_missions.sql');

describe('heidi_missions migration — static checks (no database)', () => {
  it('creates public.heidi_missions idempotently', () => {
    expect(SQL).toMatch(/CREATE TABLE IF NOT EXISTS public\.heidi_missions/);
  });

  it('has an independent uuid PK and nullable goal_id FK', () => {
    expect(SQL).toMatch(/id\s+uuid PRIMARY KEY DEFAULT gen_random_uuid\(\)/);
    expect(SQL).toMatch(/goal_id\s+uuid REFERENCES public\.heidi_goals\(id\)/);
  });

  it('enforces idempotency_key uniqueness (not goal_id)', () => {
    expect(SQL).toMatch(/UNIQUE \(idempotency_key\)/);
    // One goal must be able to own multiple missions with different work keys.
    expect(SQL).not.toMatch(/UNIQUE \(goal_id\)/);
  });

  it('status CHECK covers every lifecycle state including waiting_human and timed_out', () => {
    for (const s of ['planned', 'claimed', 'running', 'verifying',
      'waiting_human', 'succeeded', 'failed', 'cancelled', 'timed_out']) {
      expect(SQL).toContain(`'${s}'`);
    }
  });

  it('carries fencing and resume columns', () => {
    for (const c of ['claim_generation', 'attempt', 'lease_expires_at',
      'awaiting_approval_ref', 'authorized_by', 'authorized_at', 'resume_count']) {
      expect(SQL).toContain(c);
    }
  });

  it('enables RLS with a service_role-only policy', () => {
    expect(SQL).toMatch(/ENABLE ROW LEVEL SECURITY/);
    expect(SQL).toMatch(/TO service_role/);
  });
});

// ---------------------------------------------------------------------------
// Live-schema verification — harness-OWNED ephemeral container only.
//
// A shell command that "prints a DSN" proves nothing: the string could
// point at another empty DB on the active server, or anywhere else.
// Instead this harness provisions the target itself via a fixed,
// structured docker invocation and proves ownership by inspection:
//
//   - the container name is generated by THIS test run (nonce), so it
//     cannot pre-exist;
//   - `docker inspect` confirms the returned container ID, name, image,
//     and a creation timestamp inside this run;
//   - the host port is docker-assigned (-p 127.0.0.1::5432 — documented
//     syntax for "ephemeral host port") and read back via `docker port`
//     for the verified container — the harness builds the DSN itself;
//   - teardown (`docker rm -f`) runs in afterAll unconditionally.
//
// A second-layer guard remains: HYDI sentinel tables must be absent even
// on the verified container. Gate: HYDI_MISSION_TEST_CONTAINER=1.
// Skipped by default — never connects to any pre-existing instance.
// ---------------------------------------------------------------------------
const USE_CONTAINER = process.env.HYDI_MISSION_TEST_CONTAINER === '1';
const PG_IMAGE = 'postgres:16';
const PG_PASSWORD = 'hydi-mig-test';
const HYDI_SENTINEL_TABLES = [
  'heidi_events', 'heidi_goals', 'protoforge_opportunities',
  'human_intervention_requests', 'operator_escalations',
];

const liveDescribe = USE_CONTAINER ? describe : describe.skip;

liveDescribe('heidi_missions — live schema (harness-owned ephemeral Postgres)', () => {
  let client;
  let containerName = null;
  const { execSync } = require('child_process');
  const sh = (cmd) => execSync(cmd, { encoding: 'utf8', timeout: 120000 }).trim();

  beforeAll(async () => {
    // Provision: harness-generated identity — cannot pre-exist.
    containerName = `hydi-mig-test-${process.pid}-${Math.random().toString(36).slice(2, 10)}`;
    const containerId = sh(
      `docker run -d --name ${containerName} ` +
      `-e POSTGRES_PASSWORD=${PG_PASSWORD} ` +
      `-p 127.0.0.1::5432 ${PG_IMAGE}`,
    );

    // Verify ownership: inspect the container WE just created and confirm
    // identity — matching id, our nonce name, postgres image, created
    // within this run. If any check fails, refuse before connecting.
    const inspect = JSON.parse(sh(`docker inspect ${containerName}`))[0];
    const created = new Date(inspect.Created).getTime();
    const fresh = Date.now() - created < 120000;
    if (!inspect.Id.startsWith(containerId.slice(0, 12))
      || inspect.Name !== `/${containerName}`
      || !inspect.Config.Image.includes('postgres')
      || !fresh) {
      sh(`docker rm -f ${containerName}`).toString();
      containerName = null;
      throw new Error('container identity check failed — refusing to run DDL on unverified target');
    }

    // Harness-built DSN: docker assigns the port; we read it back.
    const port = sh(`docker port ${containerName} 5432`).split(':').pop();
    const dsn = `postgres://postgres:${PG_PASSWORD}@127.0.0.1:${port}/postgres`;

    // Wait for readiness (container init takes a few seconds).
    const { Client } = require('pg');
    const deadline = Date.now() + 90000;
    let connected = false;
    while (Date.now() < deadline) {
      try {
        client = new Client(dsn);
        await client.connect();
        connected = true;
        break;
      } catch {
        client = null;
        await new Promise((r) => setTimeout(r, 1500));
      }
    }
    if (!connected) throw new Error('ephemeral postgres did not become ready');

    // Second-layer guard: the verified container must be clean — a stock
    // postgres image has no HYDI objects; presence means something is
    // wrong with our provisioning assumptions.
    const { rows } = await client.query(
      `SELECT to_regclass(name) AS present FROM unnest($1::text[]) AS name`,
      [HYDI_SENTINEL_TABLES.map((t) => `public.${t}`)],
    );
    const found = rows.filter((r) => r.present !== null).map((r) => r.present);
    if (found.length > 0) {
      await client.end(); client = null;
      throw new Error(`provisioned target is not clean — HYDI objects present: ${found.join(', ')}`);
    }

    await client.query('BEGIN');
    // Minimal parent-table stubs: the migration's FKs reference
    // heidi_goals/human_intervention_requests which don't exist on a
    // disposable instance. FK semantics need only a PK of matching type.
    // Created inside the rolled-back tx — nothing persists.
    await client.query(`CREATE TABLE public.heidi_goals (id uuid PRIMARY KEY)`);
    await client.query(`CREATE TABLE public.human_intervention_requests (id uuid PRIMARY KEY)`);
    // heidi_events stub with the REAL column shape (20260626130000) —
    // needed to prove the ledger's receipt insert is schema-compatible.
    await client.query(`CREATE TABLE public.heidi_events (
      id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      event_type TEXT NOT NULL,
      division TEXT,
      payload JSONB,
      verdict TEXT,
      context_snapshot JSONB,
      memory_ids UUID[],
      created_at TIMESTAMPTZ DEFAULT now()
    )`);
    // service_role is a Supabase role — stub it (CREATE ROLE is
    // transactional in Postgres; rolls back with the rest).
    await client.query(`CREATE ROLE service_role NOLOGIN`);
    await client.query(SQL);
  }, 180000);   // container start + readiness poll can exceed the tier default

  afterAll(async () => {
    try {
      if (client) {
        await client.query('ROLLBACK').catch(() => { });
        await client.end().catch(() => { });
      }
    } finally {
      // Harness owns the container — always torn down.
      if (containerName) {
        try { sh(`docker rm -f ${containerName}`); }
        catch { console.warn(`teardown failed for ${containerName} — remove manually`); }
      }
    }
  }, 60000);

  it('rejects a status outside the CHECK (savepoint-scoped)', async () => {
    if (!client) return;   // beforeAll refused/timed out — nothing to assert
    await client.query('SAVEPOINT sp_bad_status');
    await expect(client.query(
      "INSERT INTO heidi_missions (idempotency_key, producer_key, status) VALUES ('k1','test','not_a_status')",
    )).rejects.toThrow();
    await client.query('ROLLBACK TO SAVEPOINT sp_bad_status');
  });

  it('allows two missions on one goal when work keys differ', async () => {
    if (!client) return;
    await client.query('SAVEPOINT sp_multi');
    const { rows } = await client.query(
      'INSERT INTO heidi_goals (id) VALUES (gen_random_uuid()) RETURNING id',
    );
    const goalId = rows[0].id;
    await client.query(
      'INSERT INTO heidi_missions (idempotency_key, producer_key, goal_id) VALUES ($1,$2,$3)',
      ['w1', 'test', goalId],
    );
    await client.query(
      'INSERT INTO heidi_missions (idempotency_key, producer_key, goal_id) VALUES ($1,$2,$3)',
      ['w2', 'test', goalId],
    );
    // same goal, two independent mission rows with distinct ids
    const cnt = await client.query(
      'SELECT count(*)::int AS n, count(DISTINCT id)::int AS distinct_ids FROM heidi_missions WHERE goal_id=$1',
      [goalId],
    );
    expect(cnt.rows[0].n).toBe(2);
    expect(cnt.rows[0].distinct_ids).toBe(2);
    await client.query('ROLLBACK TO SAVEPOINT sp_multi');
  });

  it('accepts the ledger claim insert pair (mission row + heidi_events receipt)', async () => {
    if (!client) return;
    await client.query('SAVEPOINT sp_claim');
    // Mirrors MissionLedger.claim()'s exact insert shapes — a schema
    // drift on either table breaks here, not in production.
    const m = await client.query(
      `INSERT INTO heidi_missions
         (id, goal_id, idempotency_key, producer_key, capability_id, params_hash,
          status, stage, attempt, claim_generation, claimed_by, claimed_at, lease_expires_at)
       VALUES (gen_random_uuid(), NULL, 'rt-claim-1', 'mission_runner', 'ops.test', 'hash',
               'claimed', 'DISPATCHED', 1, 1, 'test', now(), now()+interval '5 minutes')
       RETURNING id`,
    );
    const missionId = m.rows[0].id;
    await client.query(
      `INSERT INTO heidi_events (event_type, division, payload, created_at)
       VALUES ('mission_transition', 'missions', $1::jsonb, now())`,
      [JSON.stringify({ missionId, toStage: 'DISPATCHED', claimGeneration: 1, stream: 'execution' })],
    );
    // And the fenced transition write must apply under the legal predicate
    const t = await client.query(
      `UPDATE heidi_missions SET status='running', stage='RUNNING'
       WHERE id=$1 AND claim_generation=1 AND status = ANY('{claimed}'::text[])
       RETURNING id`,
      [missionId],
    );
    expect(t.rows).toHaveLength(1);
    // …and must refuse an illegal jump — after RUNNING the row is
    // 'running'; 'succeeded' is only legal from 'verifying' (mirrors
    // LEGAL_TRANSITIONS), so this update must match nothing.
    const bad = await client.query(
      `UPDATE heidi_missions SET status='succeeded'
       WHERE id=$1 AND claim_generation=1 AND status = ANY('{verifying}'::text[])
       RETURNING id`,
      [missionId],
    );
    expect(bad.rows).toHaveLength(0);
    await client.query('ROLLBACK TO SAVEPOINT sp_claim');
  });
});
