const path = require('path');
const fs = require('fs');
const { loadManifest } = require('../../protoforge/packages/application-manifest/src/index');
const { ApplicationRegistry } = require('../../protoforge/packages/application-registry/src/index');
const { validate } = require('../../protoforge/tools/validate-app/src/validator');

const PROTO_YI_DIR = path.join(process.cwd(), 'protoforge-applications', 'proto-yi');

describe('Proto YI — first factory product', () => {
  test('was generated by create-app', () => {
    expect(fs.existsSync(PROTO_YI_DIR)).toBe(true);
    expect(fs.existsSync(path.join(PROTO_YI_DIR, 'package.json'))).toBe(true);
    expect(fs.existsSync(path.join(PROTO_YI_DIR, 'manifest.json'))).toBe(true);
    expect(fs.existsSync(path.join(PROTO_YI_DIR, 'src', 'index.js'))).toBe(true);
  });

  test('has a valid manifest', () => {
    const loaded = loadManifest(path.join(PROTO_YI_DIR, 'manifest.json'));
    expect(loaded.ok).toBe(true);
    expect(loaded.manifest.name).toBe('Proto YI');
    expect(loaded.manifest.version).toBe('0.1.0');
  });

  test('is registered in the application registry', () => {
    const registry = new ApplicationRegistry({ autoLoad: true });
    const app = registry.get('proto-yi');
    expect(app).not.toBeNull();
    expect(app.name).toBe('Proto YI');
  });

  test('passes validate-app', () => {
    const result = validate(PROTO_YI_DIR);
    expect(result.ok).toBe(true);
    expect(result.manifest.name).toBe('Proto YI');
  });

  test('has the standardized factory structure', () => {
    expect(fs.existsSync(path.join(PROTO_YI_DIR, 'src', 'api', 'router.js'))).toBe(true);
    expect(fs.existsSync(path.join(PROTO_YI_DIR, 'src', 'events', 'event-bus.js'))).toBe(true);
    expect(fs.existsSync(path.join(PROTO_YI_DIR, 'src', 'persistence', 'json-store.js'))).toBe(true);
    expect(fs.existsSync(path.join(PROTO_YI_DIR, 'tests', 'blueprint.test.js'))).toBe(true);
  });
});
